"use client"

import { useState, useRef, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/forms-and-input/textarea"
import { Send, Loader2, ChevronDown, ChevronRight } from "lucide-react"
import { REQUEST_TYPES } from "@/lib/prompts/request-types"
import ModalUrlPrompt from "@/components/ui/modals/modal-url-prompt"

export default function StreamingChat({ 
  projectId, 
  projectName, 
  autoGeneratePrompt, 
  onAutoGenerateComplete, 
  onCodeGenerated, 
  onGenerationStart, 
  onGenerationEnd, 
  isProjectReady 
}) {
  const [inputMessage, setInputMessage] = useState("")
  const [messages, setMessages] = useState([
    {
      role: "assistant",
      content: "hi! i'm **chromie**, your chrome extension assistant. tell me what you'd like in your extension.",
    },
  ])
  const [isGenerating, setIsGenerating] = useState(false)
  const [hasGeneratedCode, setHasGeneratedCode] = useState(false)
  const [streamingMessage, setStreamingMessage] = useState(null)
  const [currentThinking, setCurrentThinking] = useState("")
  const [currentCode, setCurrentCode] = useState("")
  const [phaseSummaries, setPhaseSummaries] = useState({ analyzing: null, planning: null, implementing: null })
  const [urlPromptData, setUrlPromptData] = useState(null)
  const [showUrlPrompt, setShowUrlPrompt] = useState(false)
  const [isThinkingExpanded, setIsThinkingExpanded] = useState(false)
  const messagesEndRef = useRef(null)
  const thinkingBufferRef = useRef("")
  const codeBufferRef = useRef("")
  const bufferTimeoutRef = useRef(null)
  const autoGeneratedRef = useRef(false)
  const currentRequestRef = useRef(null)
  const finalMessageAddedRef = useRef(false)

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" })
  }

  // Debug logging
  useEffect(() => {
    console.log('StreamingChat component mounted with props:', { projectId, isProjectReady })
  }, [projectId, isProjectReady])

  // Buffer function is no longer needed since we show summaries instead of raw content

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (bufferTimeoutRef.current) {
        clearTimeout(bufferTimeoutRef.current)
      }
    }
  }, [])

  // Only scroll to bottom when assistant messages are added or streaming content changes
  useEffect(() => {
    if (messages.length > 0) {
      const lastMessage = messages[messages.length - 1]
      if (lastMessage.role === 'assistant') {
        scrollToBottom()
      }
    }
  }, [messages])
  
  // Scroll when streaming content changes
  useEffect(() => {
    if (streamingMessage || currentThinking || currentCode) {
      scrollToBottom()
    }
  }, [streamingMessage, currentThinking, currentCode])

  useEffect(() => {
    if (autoGeneratePrompt && isProjectReady && !hasGeneratedCode && !isGenerating && !autoGeneratedRef.current) {
      console.log('🚀 Auto-generating with prompt:', autoGeneratePrompt)
      autoGeneratedRef.current = true // Prevent duplicate auto-generation
      setInputMessage(autoGeneratePrompt)
      
      // Add the user message immediately
      const userMessage = {
        role: "user",
        content: autoGeneratePrompt,
      }
      setMessages((prev) => [...prev, userMessage])
      
      // Start the generation process
      startGeneration(autoGeneratePrompt, true) // true indicates this is auto-generation
    }
  }, [autoGeneratePrompt, isProjectReady, hasGeneratedCode, isGenerating])

  const startGeneration = async (prompt, isAutoGeneration = false) => {
    if (isGenerating) return
    
    setIsGenerating(true)
    setStreamingMessage(null)
    setCurrentThinking("")
    setCurrentCode("")
    setPhaseSummaries({ analyzing: null, planning: null, implementing: null })
    setIsThinkingExpanded(false)
    
    // Reset buffers
    thinkingBufferRef.current = ""
    codeBufferRef.current = ""
    
    // Reset final message flag
    finalMessageAddedRef.current = false
    
    // Clear any existing timeouts
    if (bufferTimeoutRef.current) {
      clearTimeout(bufferTimeoutRef.current)
    }

    if (onGenerationStart) {
      onGenerationStart()
    }

    try {
      console.log(`🔍 hasGeneratedCode: ${hasGeneratedCode}, projectId: ${projectId}`)
      
      // Force refresh hasGeneratedCode from Supabase before determining request type
      let currentHasGeneratedCode = hasGeneratedCode
      if (projectId) {
        try {
          const response = await fetch(`/api/projects/${projectId}/has-generated-code`)
          if (response.ok) {
            const data = await response.json()
            currentHasGeneratedCode = data.hasGeneratedCode
            if (data.hasGeneratedCode !== hasGeneratedCode) {
              console.log(`🔍 hasGeneratedCode updated: ${hasGeneratedCode} → ${data.hasGeneratedCode}`)
              setHasGeneratedCode(data.hasGeneratedCode)
            }
          }
        } catch (error) {
          console.error('Error refreshing hasGeneratedCode:', error)
        }
      }
      
      const requestType = currentHasGeneratedCode ? REQUEST_TYPES.ADD_TO_EXISTING : REQUEST_TYPES.NEW_EXTENSION
      console.log(`🔄 Request type: ${requestType}`)

      // Start streaming response
      const response = await fetch("/api/generate/stream", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          prompt: prompt,
          projectId,
          requestType: requestType,
        }),
      })

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }

      const reader = response.body.getReader()
      const decoder = new TextDecoder()
      let buffer = ""

      while (true) {
        const { done, value } = await reader.read()
        if (done) break

        buffer += decoder.decode(value, { stream: true })
        const lines = buffer.split('\n')
        buffer = lines.pop() || ""

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            try {
              const data = JSON.parse(line.slice(6))
              console.log('📡 Stream chunk:', data)

              switch (data.type) {
                case "start":
                  // ignore placeholder status in UI
                  break
                
                case "analyzing":
                  // ignore placeholder status in UI
                  break
                
                case "analysis_complete":
                  // ignore placeholder status in UI
                  break
                
                case "fetching_apis":
                  // ignore placeholder status in UI
                  break
                
                case "apis_ready":
                  // ignore placeholder status in UI
                  break
                
                case "scraping":
                  // ignore placeholder status in UI
                  break
                
                case "scraping_complete":
                  // ignore placeholder status in UI
                  break
                
                case "scraping_skipped":
                  // ignore placeholder status in UI
                  break
                
                case "prompt_selected":
                  // ignore placeholder status in UI
                  break
                
                case "context_ready":
                  // ignore placeholder status in UI
                  break
                
                case "generation_starting":
                  // ignore placeholder status in UI
                  break
                
                case "thinking":
                  // Accumulate but do not render raw thinking tokens in UI
                  thinkingBufferRef.current += data.content
                  setCurrentThinking(thinkingBufferRef.current)
                  break

                case "thinking_complete":
                  // Do not duplicate summary here; phase:planning will render the concise summary
                  if (data.content) {
                    setPhaseSummaries(prev => ({ ...prev, planning: data.content }))
                  }
                  break

                case "phase":
                  // Update phase summaries with concise content
                  if (data.phase && data.content) {
                    console.log(`📘 Phase update: ${data.phase} →`, data.content)
                    setPhaseSummaries(prev => ({ ...prev, [data.phase]: data.content }))
                  }
                  break

                case "explanation":
                  // Store the explanation for final message
                  if (data.content) {
                    console.log(`📝 Explanation received:`, data.content)
                    setPhaseSummaries(prev => ({ ...prev, explanation: data.content }))
                  }
                  break

                case "generating_code":
                  // ignore placeholder status in UI
                  break
                
                case "code":
                  // ignore placeholder status in UI
                  break
                
                case "generation_complete":
                  // ignore placeholder status in UI
                  break

                case "requires_url":
                  // Handle URL requirement - trigger the URL prompt modal (no streaming status)
                  // Store the current request info for URL continuation
                  currentRequestRef.current = {
                    prompt: prompt,
                    requestType: requestType,
                    projectId: projectId
                  }
                  
                  // Trigger URL prompt modal
                  setUrlPromptData({
                    data: {
                      requiresUrl: true,
                      message: "This extension would benefit from analyzing specific website structure. Please choose how you'd like to proceed.",
                      detectedSites: [],
                      detectedUrls: [],
                      featureRequest: prompt,
                      requestType: requestType
                    },
                    originalPrompt: prompt
                  })
                  setShowUrlPrompt(true)
                  break

                case "error":
                  setStreamingMessage({ type: "error", content: `Error: ${data.content}` })
                  break

                case "done":
                  // Final completion
                  setStreamingMessage(null)
                  
                  // Add final assistant message only if not already added
                  if (!finalMessageAddedRef.current) {
                    const finalMessage = {
                      role: "assistant",
                      content: phaseSummaries.explanation || phaseSummaries.planning || "Extension code has been generated and saved to your project.",
                    }
                    setMessages(prev => [...prev, finalMessage])
                    finalMessageAddedRef.current = true
                  }

                  // Mark that code has been generated
                  if (!hasGeneratedCode) {
                    setHasGeneratedCode(true)
                  }

                  if (onCodeGenerated) {
                    onCodeGenerated({ success: true })
                  }

                  // Call auto-generate complete callback if this was an auto-generation
                  if (autoGeneratePrompt && onAutoGenerateComplete) {
                    onAutoGenerateComplete()
                  }
                  break
              }
            } catch (parseError) {
              console.error('Error parsing stream data:', parseError)
            }
          }
        }
      }

    } catch (error) {
      console.error("Error in streaming generation:", error)
      const errorMessage = {
        role: "assistant",
        content: `Error: ${error.message}`,
      }
      setMessages(prev => [...prev, errorMessage])
      setStreamingMessage({ type: "error", content: error.message })
    } finally {
      setIsGenerating(false)
      setStreamingMessage(null)
      setCurrentThinking("")
      setCurrentCode("")
      
      if (onGenerationEnd) {
        onGenerationEnd()
      }
    }
  }

  const startGenerationWithUrl = async (prompt, userUrl, requestType, projectId) => {
    if (isGenerating) return
    
    setIsGenerating(true)
    setStreamingMessage(null)
    setCurrentThinking("")
    setCurrentCode("")
    setPhaseSummaries({ analyzing: null, planning: null, implementing: null })
    setIsThinkingExpanded(false)
    
    // Reset buffers
    thinkingBufferRef.current = ""
    codeBufferRef.current = ""
    
    // Reset final message flag
    finalMessageAddedRef.current = false
    
    // Clear any existing timeouts
    if (bufferTimeoutRef.current) {
      clearTimeout(bufferTimeoutRef.current)
    }

    if (onGenerationStart) {
      onGenerationStart()
    }

    try {
      console.log(`🔄 Continuing generation with URL: ${userUrl}`)

      // Start streaming response with URL
      const response = await fetch("/api/generate/stream", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          prompt: prompt,
          projectId: projectId,
          requestType: requestType,
          userProvidedUrl: userUrl,
          skipScraping: false
        }),
      })

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }

      const reader = response.body.getReader()
      const decoder = new TextDecoder()
      let buffer = ""

      while (true) {
        const { done, value } = await reader.read()
        if (done) break

        buffer += decoder.decode(value, { stream: true })
        const lines = buffer.split('\n')
        buffer = lines.pop() || ""

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            try {
              const data = JSON.parse(line.slice(6))
              console.log('📡 Stream chunk (with URL):', data)

              switch (data.type) {
                case "start":
                  // ignore placeholder status in UI
                  break
                
                case "analyzing":
                  // ignore placeholder status in UI
                  break
                
                case "analysis_complete":
                  // ignore placeholder status in UI
                  break
                
                case "fetching_apis":
                  // ignore placeholder status in UI
                  break
                
                case "apis_ready":
                  // ignore placeholder status in UI
                  break
                
                case "scraping":
                  // ignore placeholder status in UI
                  break
                
                case "scraping_complete":
                  // ignore placeholder status in UI
                  break
                
                case "scraping_skipped":
                  // ignore placeholder status in UI
                  break
                
                case "prompt_selected":
                  // ignore placeholder status in UI
                  break
                
                case "context_ready":
                  // ignore placeholder status in UI
                  break
                
                case "generation_starting":
                  // ignore placeholder status in UI
                  break
                
                case "thinking":
                  // Accumulate but do not render raw thinking tokens in UI
                  thinkingBufferRef.current += data.content
                  setCurrentThinking(thinkingBufferRef.current)
                  break

                case "thinking_complete":
                  if (data.content) {
                    setPhaseSummaries(prev => ({ ...prev, planning: data.content }))
                  }
                  break

                case "phase":
                  if (data.phase && data.content) {
                    console.log(`📘 Phase update (with URL): ${data.phase} →`, data.content)
                    setPhaseSummaries(prev => ({ ...prev, [data.phase]: data.content }))
                  }
                  break

                case "explanation":
                  // Store the explanation for final message
                  if (data.content) {
                    console.log(`📝 Explanation received (with URL):`, data.content)
                    setPhaseSummaries(prev => ({ ...prev, explanation: data.content }))
                  }
                  break

                case "generating_code":
                  // ignore placeholder status in UI
                  break
                
                case "code":
                  // ignore placeholder status in UI
                  break
                
                case "generation_complete":
                  // ignore placeholder status in UI
                  break

                case "requires_url":
                  // This shouldn't happen again; ignore status and continue
                  break

                case "error":
                  setStreamingMessage({ type: "error", content: `Error: ${data.content}` })
                  break

                case "done":
                  // Final completion
                  setStreamingMessage(null)
                  
                  // Add final assistant message only if not already added
                  if (!finalMessageAddedRef.current) {
                    const finalMessage = {
                      role: "assistant",
                      content: phaseSummaries.explanation || phaseSummaries.planning || "Extension code has been generated and saved to your project.",
                    }
                    setMessages(prev => [...prev, finalMessage])
                    finalMessageAddedRef.current = true
                  }

                  // Mark that code has been generated
                  if (!hasGeneratedCode) {
                    setHasGeneratedCode(true)
                  }

                  if (onCodeGenerated) {
                    onCodeGenerated({ success: true })
                  }

                  // Call auto-generate complete callback if this was an auto-generation
                  if (autoGeneratePrompt && onAutoGenerateComplete) {
                    onAutoGenerateComplete()
                  }
                  break
              }
            } catch (parseError) {
              console.error('Error parsing stream data:', parseError)
            }
          }
        }
      }

    } catch (error) {
      console.error("Error in streaming generation with URL:", error)
      const errorMessage = {
        role: "assistant",
        content: `Error: ${error.message}`,
      }
      setMessages(prev => [...prev, errorMessage])
      setStreamingMessage({ type: "error", content: error.message })
    } finally {
      setIsGenerating(false)
      setStreamingMessage(null)
      setCurrentThinking("")
      setCurrentCode("")
      currentRequestRef.current = null
      
      if (onGenerationEnd) {
        onGenerationEnd()
      }
    }
  }

  const handleSendMessage = async (e) => {
    e.preventDefault()
    if (!inputMessage.trim() || isGenerating) return

    const userMessage = {
      role: "user",
      content: inputMessage,
    }

    setMessages((prev) => [...prev, userMessage])
    const prompt = inputMessage
    setInputMessage("")
    
    // Use the same startGeneration function (false = manual generation)
    await startGeneration(prompt, false)
  }

  const handleUrlSubmit = async (data, userUrl, originalPrompt) => {
    console.log('Continuing generation with URL:', userUrl)
    setShowUrlPrompt(false)
    setUrlPromptData(null)
    
    // Continue generation with the URL using the stored request info
    const requestInfo = currentRequestRef.current
    if (requestInfo) {
      await startGenerationWithUrl(requestInfo.prompt, userUrl, requestInfo.requestType, requestInfo.projectId)
    }
  }

  const handleUrlCancel = () => {
    console.log('URL prompt cancelled')
    setShowUrlPrompt(false)
    setUrlPromptData(null)
    setIsGenerating(false)
    setStreamingMessage(null)
  }

  const renderThinkingSection = () => {
    // Show if we have thinking content, phase summaries, or are currently thinking
    const hasThinkingContent = currentThinking && currentThinking.trim().length > 0
    const hasPhases = phaseSummaries.analyzing || phaseSummaries.planning || phaseSummaries.implementing
    
    if (!hasThinkingContent && !hasPhases && !isGenerating) return null
    
    // Determine if thinking is complete (generation finished and we have content)
    const isThinkingComplete = !isGenerating && (hasThinkingContent || hasPhases)
    
    return (
      <div className="mb-2">
        <div 
          className="flex items-center space-x-2 cursor-pointer text-gray-400 hover:text-gray-300 hover:bg-gray-800/30 transition-colors py-2 px-2 rounded-md -mx-2"
          onClick={() => setIsThinkingExpanded(!isThinkingExpanded)}
        >
          <div className="flex items-center space-x-2">
            {isThinkingExpanded ? <ChevronDown className="h-4 w-4 flex-shrink-0" /> : <ChevronRight className="h-4 w-4 flex-shrink-0" />}
            {isGenerating ? (
              <span className="text-sm font-medium">
                thinking
                <span className="thinking-dots">
                  <span className="dot-1">.</span>
                  <span className="dot-2">.</span>
                  <span className="dot-3">.</span>
                </span>
              </span>
            ) : (
              <span className="text-sm font-medium">
                {isThinkingComplete ? "thinking complete" : "thinking"}
              </span>
            )}
          </div>
        </div>
        
        {isThinkingExpanded && hasPhases && (
          <div className="mt-2 space-y-2">
            {/* Phase summaries */}
            {phaseSummaries.analyzing && (
              <div className="p-3 rounded-lg border text-blue-300 bg-blue-900/10 border-blue-500/20">
                <div className="text-xs uppercase tracking-wide mb-1">Analyzing</div>
                <div className="text-sm whitespace-pre-wrap leading-relaxed">{phaseSummaries.analyzing}</div>
              </div>
            )}
            {phaseSummaries.planning && (
              <div className="p-3 rounded-lg border text-yellow-300 bg-yellow-900/10 border-yellow-500/20">
                <div className="text-xs uppercase tracking-wide mb-1">Implementing</div>
                <div className="text-sm whitespace-pre-wrap leading-relaxed">{phaseSummaries.planning}</div>
              </div>
            )}
          </div>
        )}
        
      </div>
    )
  }

  const renderStreamingMessage = () => {
    const hasStreaming = !!streamingMessage

    if (!hasStreaming) return null

    const getMessageStyle = () => {
      switch (streamingMessage.type) {
        case "status":
          return "text-blue-400 bg-blue-900/20 border-blue-500/30"
        case "thinking":
        case "thinking_complete":
          return "text-yellow-400 bg-yellow-900/20 border-yellow-500/30"
        case "generating_code":
        case "code":
          return "text-green-400 bg-green-900/20 border-green-500/30"
        case "error":
          return "text-red-400 bg-red-900/20 border-red-500/30"
        default:
          return "text-gray-400 bg-gray-900/20 border-gray-500/30"
      }
    }

    const getIcon = () => {
      switch (streamingMessage.type) {
        case "status":
          return "•"
        case "thinking":
        case "thinking_complete":
          return "•"
        case "generating_code":
        case "code":
          return "•"
        case "error":
          return "•"
        default:
          return "•"
      }
    }

    return (
      <div className={`p-3 rounded-lg border ${getMessageStyle()} mb-2`}>
        <div className="flex items-start space-x-2">
          <span className="text-lg">{getIcon()}</span>
          <div className="flex-1">
            <div className="text-sm font-medium mb-1">
              {streamingMessage.type === "thinking" && "Planning"}
              {streamingMessage.type === "thinking_complete" && null}
              {streamingMessage.type === "generating_code" && "Creating extension"}
              {streamingMessage.type === "code" && "Writing code"}
              {streamingMessage.type === "status" && "Processing"}
              {streamingMessage.type === "error" && "Error"}
              {streamingMessage.type === "requires_url" && "URL required"}
              {streamingMessage.type === "generation_complete" && "Complete"}
            </div>
            <div className="text-sm whitespace-pre-wrap leading-relaxed">
              {streamingMessage.content}
              {streamingMessage.type === "code" && (
                <span className="inline-block w-2 h-4 bg-green-400 ml-1 animate-pulse"></span>
              )}
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="flex flex-col h-full">
      {/* Chat Header */}
      <div className="p-4 border-b border-white/10">
        <p className="text-sm text-gray-400">
          {projectName || "describe what you want to add or modify"}
        </p>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto custom-scrollbar p-4 space-y-4 bg-gradient-to-b from-slate-800/30 to-slate-900/30">
        {messages.map((message, index) => (
          <div
            key={index}
            className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}
          >
            <div
              className={`max-w-[80%] p-3 rounded-lg ${
                message.role === "user"
                  ? "bg-gradient-to-r from-purple-500 to-blue-500 text-white"
                  : "bg-slate-700/50 text-gray-200 border border-slate-600"
              }`}
            >
              <div className="whitespace-pre-wrap">{message.content}</div>
            </div>
          </div>
        ))}
        
        {/* Thinking section */}
        {renderThinkingSection()}
        
        {/* Streaming message */}
        {renderStreamingMessage()}
        
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="p-4 border-t border-white/10">
        <form onSubmit={handleSendMessage} className="space-y-3">
          <Textarea
            value={inputMessage}
            onChange={(e) => setInputMessage(e.target.value)}
            placeholder={projectName ? `describe what you want to add or modify in ${projectName}...` : "describe what you want to add or modify..."}
            className="min-h-[80px] bg-slate-700/50 border-slate-600 text-white placeholder:text-slate-400 resize-none"
          />
          <Button
            type="submit"
            disabled={!inputMessage.trim() || isGenerating || !projectId}
            className="w-full bg-gradient-to-r from-purple-500 to-blue-500 hover:from-purple-600 hover:to-blue-600 disabled:opacity-50"
          >
            {isGenerating ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                generating...
              </>
            ) : !projectId ? (
              "setting up project..."
            ) : (
              <>
                <Send className="h-4 w-4 mr-2" />
                send
              </>
            )}
          </Button>
        </form>
      </div>

      {/* URL Prompt Modal */}
      {showUrlPrompt && urlPromptData && (
        <ModalUrlPrompt
          data={urlPromptData.data}
          originalPrompt={urlPromptData.originalPrompt}
          onUrlSubmit={handleUrlSubmit}
          onCancel={handleUrlCancel}
          onCodeGenerated={onCodeGenerated}
          projectId={projectId}
          hasGeneratedCode={hasGeneratedCode}
          onGenerationEnd={onGenerationEnd}
        />
      )}
    </div>
  )
}
