import { Suspense } from "react"                                                                                                                                                                                                                                             
 import DeploymentPage from "@/components/pages/deployment-page"                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                              
 export default function Page() {                                                                                                                                                                                                                                             
   return (                                                                                                                                                                                                                                                                   
     <Suspense fallback={<div>Loading...</div>}>                                                                                                                                                                                                                              
       <DeploymentPage />                                                                                                                                                                                                                                                     
     </Suspense>                                                                                                                                                                                                                                                              
   )                                                                                                                                                                                                                                                                          
 }