-- Create metrics_events table for tracking Chrome extension analytics
-- Designed for high-volume ingestion with future scalability in mind
CREATE TABLE IF NOT EXISTS public.metrics_events (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  user_uuid text, -- Anonymous Chrome user ID from SDK
  event_type text NOT NULL, -- e.g. 'install', 'uninstall', 'button_click', 'frontend_displayed'
  event_time timestamptz NOT NULL DEFAULT now(),
  metadata jsonb, -- Optional context (e.g., {label: 'save_button', value: 42})
  received_at timestamptz NOT NULL DEFAULT now(), -- Set by backend ingest
  batch_id uuid, -- Optional, for grouping batched uploads
  source text NOT NULL DEFAULT 'sdk' -- 'sdk', 'api', 'import', etc.
);

-- Indexes for performance and common query patterns
CREATE INDEX IF NOT EXISTS idx_metrics_events_project_id ON public.metrics_events(project_id);
CREATE INDEX IF NOT EXISTS idx_metrics_events_event_time ON public.metrics_events(event_time DESC);
CREATE INDEX IF NOT EXISTS idx_metrics_events_event_type ON public.metrics_events(event_type);
CREATE INDEX IF NOT EXISTS idx_metrics_events_project_time ON public.metrics_events(project_id, event_time DESC);
CREATE INDEX IF NOT EXISTS idx_metrics_events_batch_id ON public.metrics_events(batch_id) WHERE batch_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_metrics_events_user_uuid ON public.metrics_events(user_uuid) WHERE user_uuid IS NOT NULL;

-- Composite index for common analytics queries (project + event_type + time range)
CREATE INDEX IF NOT EXISTS idx_metrics_events_project_type_time ON public.metrics_events(project_id, event_type, event_time DESC);

-- Enable RLS
ALTER TABLE public.metrics_events ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Users can only access metrics for projects they own

-- SELECT: Users can view metrics for their own projects
CREATE POLICY metrics_events_select_own_projects
  ON public.metrics_events
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.projects
      WHERE projects.id = metrics_events.project_id
      AND projects.user_id = auth.uid()
    )
  );

-- INSERT: Users can insert metrics for their own projects
-- Note: For SDK ingestion, you may need to use service role or create a separate
-- authenticated endpoint that validates project ownership server-side
CREATE POLICY metrics_events_insert_own_projects
  ON public.metrics_events
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.projects
      WHERE projects.id = metrics_events.project_id
      AND projects.user_id = auth.uid()
    )
  );

-- No UPDATE/DELETE policies - metrics are immutable event logs

-- Add comments
COMMENT ON TABLE public.metrics_events IS 'Stores analytics events from Chrome extensions for observability and metrics';
COMMENT ON COLUMN public.metrics_events.id IS 'Auto-incrementing bigint for high-volume inserts (better than UUID for analytics)';
COMMENT ON COLUMN public.metrics_events.project_id IS 'Foreign key to projects table';
COMMENT ON COLUMN public.metrics_events.user_uuid IS 'Anonymous Chrome user identifier from SDK';
COMMENT ON COLUMN public.metrics_events.event_type IS 'Type of event (install, uninstall, button_click, etc.)';
COMMENT ON COLUMN public.metrics_events.event_time IS 'When the event occurred (from client/SDK)';
COMMENT ON COLUMN public.metrics_events.metadata IS 'Optional JSON context for the event';
COMMENT ON COLUMN public.metrics_events.received_at IS 'When the event was received by the backend';
COMMENT ON COLUMN public.metrics_events.batch_id IS 'Optional UUID for grouping batched event uploads';
COMMENT ON COLUMN public.metrics_events.source IS 'Source of the event (sdk, api, import, etc.)';
